name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TBCTest.sln

      - name: Build solution
        run: dotnet build TBCTest.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test TBCTest.Tests/TBCTest.Tests.csproj --configuration Release --no-build --verbosity normal
